# .github/workflows/release.yml
name: Release project
on:
  workflow_dispatch:
  push: 
    branches: [main, master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release
        uses: huggingface/semver-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}