# 1. Generate a new release number
# 2. Write it to the .version file
# 3. Create a new commit and push
# 4. Tag that commit with the new version
name: Release project with .version
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches: [main, master]

jobs:
  release:
    name: Generate a new version number
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Generate and push version
        id: generate_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Github Action"
          npm version patch -git-tag-version=false
          # version=$(git describe --abbrev=0 --tags)
          version="v"$(npm pkg get version | xargs)
          echo $version > .version
          git tag -a $version
          git add . && git commit -m "Version $version"
          git push --follow-tags