name: Create a Version Number for NPM
on: 
  pull_request:
    types:
      - opened
      - edited
    branches: [main, master]

jobs:
  generate_version:
    name: Generate NPM version number
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Generate and push version
        id: generate_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Github Action"
          npm version patch && git push --follow-tags
