name: Create a Version Number
on: 
  workflow_dispatch:
  push: 
    branches: [main, master, develop]

jobs:
  versioning:
    name: Generate version numbers
    permissions: write-all

    runs-on: ubuntu-latest
    outputs:
      full_version_tag: ${{ steps.getalltags.outputs.full_version_tag }}
      next_major_tag: ${{ steps.getalltags.outputs.next_major_tag }}
      next_minor_tag: ${{ steps.getalltags.outputs.next_minor_tag }}
      next_patch_tag: ${{ steps.getalltags.outputs.next_patch_tag }}
      branchname: ${{ steps.versioninfo.outputs.branchname }}
      commithash: ${{ steps.versioninfo.outputs.commithash }}
      buildtimestamp: ${{ steps.versioninfo.outputs.buildtimestamp }}
      lastmajordigit: ${{ steps.versioninfo.outputs.lastmajordigit }}
      lastminordigit: ${{ steps.versioninfo.outputs.lastminordigit }}
      lastpatchdigit: ${{ steps.versioninfo.outputs.lastpatchdigit }}
      lastversion: ${{ steps.versioninfo.outputs.lastversion }}
      nextmajordigit: ${{ steps.selectversion.outputs.nextmajordigit }}
      nextminordigit: ${{ steps.selectversion.outputs.nextminordigit }}
      nextpatchdigit: ${{ steps.selectversion.outputs.nextpatchdigit }}
      buildversion: ${{ steps.selectversion.outputs.buildversion }}
      buildversionfilename: ${{ steps.selectversion.outputs.buildversionfilename }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get version data
        id: getalltags
        run: |
          # create all possible next versions
          declare full_version_tag=$(git describe --tags 2>/dev/null || echo "0.0.0")
          echo "full_version_tag = $full_version_tag" >> $GITHUB_OUTPUT
          echo "full_version_tag = $full_version_tag"
          
          declare next_major_tag=$( echo $full_version_tag | cut -d'.' -f1-3 | awk -F'.' '{print $1+1"."$2-$2"."$3-$3}')
          echo "next_major_tag = $next_major_tag" >> $GITHUB_OUTPUT
          echo "next_major_tag = $next_major_tag"

          declare next_minor_tag=$( echo $full_version_tag | cut -d'.' -f1-3 | awk -F'.' '{print $1"."$2+1"."$3-$3}')
          echo "next_minor_tag = $next_minor_tag" >> $GITHUB_OUTPUT
          echo "next_minor_tag = $next_minor_tag"

          declare next_patch_tag=$( echo $full_version_tag | cut -d'.' -f1-3 | awk -F'.' '{print $1"."$2"."$3+1}')
          echo "next_patch_tag = $next_patch_tag" >> $GITHUB_OUTPUT
          echo "next_patch_tag = $next_patch_tag"

          echo "extract branch name from github_ref '${{ github.ref }}'"
          declare branchname=$(echo "${{ github.ref }}" | cut -d'/' -f 3-)
          echo "clean branch name = $branchname"
          echo "extract commit short hash : $(git rev-parse --short HEAD)"
          declare commithash=$(git rev-parse --short HEAD)
          echo "extract build timestamp"
          declare buildtimestamp=$(date "+%Y-%b-%d-%H:%M:%S")
          echo "buildtimestamp = $buildtimestamp"
          declare fulltag=$(git describe --tag $(git rev-parse --verify refs/remotes/origin/main) 2>/dev/null || echo "0.0.0")
          echo "fulltag = [$fulltag]"
          declare versiontag=$(echo $fulltag | cut -d'-' -f1)
          echo "extract SemVer numbers from version tag [$versiontag]"
          declare -i lastmajordigit=$(echo $versiontag | cut -c 1- | cut -d'.' -f1)
          echo "lastmajordigit = $lastmajordigit"
          declare -i lastminordigit=$(echo $versiontag | cut -c 1- | cut -d'.' -f2)
          echo "lastminordigit = $lastminordigit"
          declare -i lastpatchdigit=$(echo $versiontag | cut -c 1- | cut -d'.' -f3)
          echo "lastpatchdigit = $lastpatchdigit"
          declare lastversion="v$lastmajordigit.$lastminordigit.$lastpatchdigit"
          echo "output variables to GitHub Actions"
          echo "branchname=$branchname" >> $GITHUB_OUTPUT
          echo "lastmajordigit=$lastmajordigit" >> $GITHUB_OUTPUT
          echo "lastminordigit=$lastminordigit" >> $GITHUB_OUTPUT
          echo "lastpatchdigit=$lastpatchdigit" >> $GITHUB_OUTPUT
          echo "commithash=$commithash" >> $GITHUB_OUTPUT
          echo "buildtimestamp=$buildtimestamp" >> $GITHUB_OUTPUT
          echo "lastversion=$lastversion" >> $GITHUB_OUTPUT
